### ISSUE TITLE
Non-negative alpha constraint and other concerns

### ISSUE THREAD

**Issue by ayhyap** [Optimization-AI/LibAUC#9]
The paper mentions a constraint on alpha to be positive, but there is no such constraint in the AUCMLoss class implementation.

Also, couldn't the negative alpha-squared term in the loss theoretically dominate if alpha becomes large enough?
What's stopping the training process from minimizing the loss by making the alpha term extremely big and consequently exploding?
`(P-a)^2 + (N-b)^2 + 2α(m-a+b)-α^2`

Overall, I don't understand what alpha even is, nor do I understand how the conjugate equality (which is where alpha seems to come from) allows you to substitute `(m-a+b)^2` with `2α(m-a+b)-α^2`.

Why not optimize the squared hinge loss `(max(m-a+b,0))^2` directly?

**Comment by yzhuoning** [comment]
The alpha is an auxiliary term that is introduced in deriving min-max formulation from min formulation of AUC. The value of alpha typically is not too large (e.g., < 1).  The alpha constraint is implemented in the optimizer instead of loss when updating the alpha (by using a clipping function). 

You can also optimize the pairwise AUC by applying different surrogate losses, e.g., squared hinge loss, however, it may not be a good choice for some settings (e.g., in online setting, sample comes one at a time) since this formulation requires pairwise data and min-max formulation of AUC could be a better choice.
